[package]
name = "vm_translator"
version = "0.1.0"
edition = "2021"
author = "xpanvictor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
